apiVersion: apps/v1  
kind: Deployment 
metadata: 
  name: hello-deployment 
spec: 
  selector: 
    matchLabels: 
      app: hello 
  replicas: 3  
  template: 
    metadata: 
      labels: 
        app: hello 
    spec: 
      containers: 
      - name: hello 
        image: karthequian/helloworld:latest 
        ports: 
        - containerPort: 80 
