kind: Service 
apiVersion: v1 
metadata: 
  name: hello-service 
spec: 
  selector: 
    app: hello 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 31000 
  type: NodePort 